<svelte:head>
  <title>Terms of Service · Replyra</title>
  <meta name="description" content="Terms of Service for Replyra, operated by PT Creative Shine Innovation." />
</svelte:head>

<h1>Terms of Service</h1>
<p class="updated">Last updated: 25 September 2026</p>

<p>
  These terms govern your use of Replyra, operated by <strong>PT CREATIVE SHINE INNOVATION</strong> ("we"). By using
  Replyra you agree to them.
</p>

<h2>1. The service</h2>
<p>
  Replyra helps businesses manage comments on their own Instagram Professional accounts and Facebook Pages: it
  classifies comments, drafts replies, and sends replies or hides comments according to rules you control.
</p>

<h2>2. Your account and connected assets</h2>
<ul>
  <li>You must have the right to manage every Instagram account or Facebook Page you connect.</li>
  <li>You are responsible for your workspace members and for keeping your login secure.</li>
  <li>You must follow Meta's Platform Terms and Instagram/Facebook Community Guidelines.</li>
</ul>

<h2>3. AI-generated replies</h2>
<p>
  Drafts are generated by AI and may be inaccurate. You decide which replies are sent automatically and which require
  approval, and you remain responsible for content published on your accounts.
</p>

<h2>4. Acceptable use</h2>
<p>Do not use Replyra to send spam, harass people, or violate the law or anyone's rights, and do not attempt to disrupt or reverse-engineer the service.</p>

<h2>5. Plans and quota</h2>
<p>Paid plans include a monthly AI quota. When it runs out, AI processing pauses and comments go to manual review; no comments are lost.</p>

<h2>6. Liability</h2>
<p>Replyra is provided "as is". To the extent permitted by law, we are not liable for indirect losses or for actions taken by Meta on your accounts.</p>

<h2>7. Termination</h2>
<p>You may stop using Replyra and disconnect your accounts at any time. We may suspend accounts that breach these terms.</p>

<h2>8. Governing law</h2>
<p>These terms are governed by the laws of the Republic of Indonesia.</p>

<h2>9. Contact</h2>
<p><a href="mailto:hello.infocreativeshine@gmail.com">hello.infocreativeshine@gmail.com</a></p>
